# Generated by Django 2.2 on 2021-04-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoriales', '0001_initial'),
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('paginas', models.IntegerField()),
                ('autores', models.ManyToManyField(related_name='libros', to='autores.Autor')),
                ('editorial', models.ForeignKey(on_delete=True, related_name='libros', to='editoriales.Editorial')),
            ],
        ),
    ]
