# Generated by Django 2.2 on 2021-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(null=True, on_delete=True, related_name='libros', to='editoriales.Editorial'),
        ),
    ]
